Repository ntu-se7-grp3/garang-guni-mobile, pull requests merged in 2024-11, with the labels that each got.

#14 feat: Add Schedule/Booking, Profile, Camera, and Related Pages
  app.json
  app/(auth)/ChangePassword.jsx
  app/(auth)/ForgotPassword.jsx
  app/(auth)/Login.jsx
  app/(auth)/SignUp.jsx
  app/(drawer)/(tabs)/_layout.jsx
  app/(drawer)/(tabs)/profile/EditProfile.jsx
  app/(drawer)/(tabs)/profile/Profile.jsx
  app/(drawer)/(tabs)/profile/_layout.jsx
  app/(drawer)/(tabs)/schedule/Schedule.jsx
  app/(drawer)/(tabs)/schedule/SchedulePickUp.jsx
  app/(drawer)/(tabs)/schedule/_layout.jsx
  app/(drawer)/history/TransactionHistory.jsx
  app/Onboarding.jsx
  app/camera/Camera.jsx
  assets/upload-photo.png
  common.js
  components/AppDrawer.jsx
  components/BookingContainer.jsx
  components/CheckBox.jsx
  components/CheckBoxList.jsx
  components/DefaultBookingContainer.jsx
  components/DefaultBookingHistoryContainer.jsx
  components/TabHeader.jsx
  constants/fakeBooking.js
  constants/fakeGetUserResponse.json
  constants/fakeImgs.js
  constants/fakeLoginResponse.json
  constants/fakeRegisterResponse.json
  constants/routes.js
  constants/theme.js
  contexts/AuthContext.jsx
  package-lock.json
  package.json
  utils/bookingUtils.js
Labels: enhancement, priority: high

#4 #3 added home-page
  app/(drawer)/(tabs)/home/Home.jsx
  assets/home/bullet.png
  assets/home/home-coin.png
  assets/home/home-item1.png
  assets/home/home-item2.png
  assets/home/home-item3.png
  assets/home/home-locate.png
  assets/home/home-schedule.png
Labels: good first issue

#10 add rates page #9
  app/(drawer)/rates/Rates.jsx
Labels: good first issue

#12 add setting page #11
  app/(auth)/ChangePassword.jsx
  app/(auth)/ForgotPassword.jsx
  app/(auth)/Login.jsx
  app/(auth)/SignUp.jsx
  app/(auth)/Welcome.jsx
  app/(drawer)/(tabs)/home/Home.jsx
  app/(drawer)/settings/Settings.jsx
  app/Onboarding.jsx
  package-lock.json
  package.json
Labels: good first issue

#8 add contact-us page #7
  app/(drawer)/(tabs)/contact-us/ContactUs.jsx
Labels: good first issue

#16 Fix css and added different lang for settings
  app/(auth)/ChangePassword.jsx
  app/(drawer)/(tabs)/contact-us/ContactUs.jsx
  app/(drawer)/(tabs)/home/Home.jsx
  app/(drawer)/rates/Rates.jsx
  app/(drawer)/settings/Settings.jsx
  components/Button.jsx
  components/Input.jsx
  constants/theme.js
  translations/en/Settings.json
  translations/ms/Settings.json
  translations/ta/Settings.json
  translations/zh/Settings.json
Labels: enhancement, priority: low

#17 fix css and misspelling of reschedule
  app/(drawer)/(tabs)/drop-off/DropOff.jsx
  app/(drawer)/(tabs)/schedule/Schedule.jsx
Labels: enhancement
